Add the missing license file
hyperledger/sawtooth-sdk-go pull request #45
Opened 2021-04-18 07:51 UTC by arsulegai

Signed-off-by: S m, Aruna <arun.s.m.cse@gmail.com>

2021-04-19 13:18 UTC, agunde406 approved these changes

2021-04-19 13:21 UTC, agunde406 requested changes
This license includes items at the end that were added for c++ specific dependencies. I don't believe those are required for the go sdk.

2021-04-19 13:40 UTC, arsulegai commented
> This license includes items at the end that were added for c++ specific dependencies. I don't believe those are required for the go sdk.

Removed, thanks for catching that. I blindly copied the file.

2021-04-19 13:42 UTC, agunde406 approved these changes

2021-05-26 19:26 UTC, dplumb94 approved these changes

2021-05-26 19:27 UTC, merged